name: 'user-web'
port: '8021'
user_srv:
  host: '127.0.0.1'
  port: '8088'
  name: 'user-srv'
jwt:
  key: '9RaY%%iHYw!iYF0VIxJ$'

sms:
  key: 'LTAI5tPdnfPQZocK2GYEKhBo'
  secret: 'NlJPXTvEKes0Rvgi5FeWeTVcwBNC9u'
  expire: '300'
redis:
  host: 'localhost'
  port: '6379'

consul:
  host: '127.0.0.1'
  port: '8500'


